package com.example.javaspringboot.mapper;

import com.example.javaspringboot.model.Product;
import com.example.javaspringboot.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	long countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int deleteByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int insert(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int insertSelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	Product selectByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int updateByPrimaryKeySelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Thu Nov 03 12:08:44 GMT+07:00 2022
	 */
	int updateByPrimaryKey(Product row);
}