package com.example.javaspringboot.mapper;

import com.example.javaspringboot.model.Users;
import com.example.javaspringboot.model.UsersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersMapper {

    long countByExample(UsersExample example);

    int deleteByExample(UsersExample example);

    int deleteByPrimaryKey(String usersId);

    int insert(Users row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    int insertSelective(Users row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    Users selectByPrimaryKey(String usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userspeople
     *
     * @mbg.generated Thu Nov 03 12:08:44 GMT+07:00 2022
     */
    int updateByPrimaryKeySelective(Users row);

    int updateByPrimaryKey(Users row);
}